name: "Deploy to Google Cloud Run"

on:
  push:
    branches:
      - main

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: 'google-github-actions/auth@v1'
        with:
          PROJECT_ID: dicompos
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/dicompos/dicomposbackend:latest
          build-args: |
            HTTP_PORT=8080
            SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
            TOKEN_SECRET=${{ secrets.TOKEN_SECRET }}
            EMAIL_USER=${{ secrets.EMAIL_USER }}
            EMAIL_PASS=${{ secrets.EMAIL_PASS }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          image: gcr.io/dicompos/dicomposbackend:latest
          service: dicompos-backend-prod
          region: asia-southeast2
          platform: managed
          allow-unauthenticated: true
          timeout: 3m
          env_vars: |
              SUPABASE_URL=${{ secrets.SUPABASE_URL }}
              SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
              TOKEN_SECRET=${{ secrets.TOKEN_SECRET }}
              EMAIL_USER=${{ secrets.EMAIL_USER }}
              EMAIL_PASS=${{ secrets.EMAIL_PASS }}
